<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type"  content="text/html; charset=utf-8"  />
      <?php echo $this->headTitle() ?>
      <?php echo $this->headLink() ?>
      <?php echo $this->headScript() ?>
   </head>
   <body>
      <div id="container">
         <div id="container_inner">
            <div id="header">
               <span id="logo">Keyboard Shorties</span>
               <span id="right_menu">

               </span>
            </div>
            <div id="breadcrumbs">
               <?php
                  echo $this->navigation()->breadcrumbs()->setMinDepth(0);
               ?>
            </div>
            <span id="menu_outter">
               <span id="menu_inner">
                  <?php echo  $this->placeholder('sidebar') ?>
               </span>
            </span>
            <span id="content_outter">
               <span id="content_inner">
                  <?php echo $this->layout()->content; ?>
               </span>
            </span>
         </div>
      </div>
   </body>
</html>