<html>
   <body>
      <h1>API</h1>
      <h2>Introduction</h2>
      <p>Introduction goes here</p>
      <h2>Getting Started</h2>
      <p>Create a link to a 'getting started' tutorial.</p>
      <h2>Methods</h2>
      <p>The key to anything you do with the API are the methods available. The methods behave differently depending on the HTTP call method used to call them.</p>
      <p>Here are the methods at your disposal:</p>
      <h3><a href="/api/applications/">/api/applications/</a></h3>
      <p>Used to interact with the keyboard shortcuts available on Keyboard Shorties, on a per application basis.</p>
      <ul>
         <li><a href="/api/applications/#GET">GET</a></li>
         <li><a href="/api/applications/#POST">POST</a></li>
         <li><a href="/api/applications/#PUT">PUT</a></li>
         <li><a href="/api/applications/#DELETE">DELETE</a></li>
      </ul>
      <h3><a href="/api/shortcuts/">/api/shortcuts/</a></h3>
      <p>Used to interact with the individual keyboard shortcuts available on Keyboard Shorties.</p>
      <ul>
         <li><a href="/api/shortcuts/#GET">GET</a></li>
         <li><a href="/api/shortcuts/#POST">POST</a></li>
         <li><a href="/api/shortcuts/#PUT">PUT</a></li>
         <li><a href="/api/shortcuts/#DELETE">DELETE</a></li>
      </ul>
      <h2>Additional Info</h2>
      <ul>
         <li>Authentication</li>
         <li>Methods</li>
         <li>Inspiration</li>
         <li>Examples</li>
      </ul>
   </body>
</html>