<h1>Delete a Shortcut</h1>
<p>Are you sure you want to delete the keyboard shortcut <b><?php echo $this->shortcut->getAction(); ?></b>?</p>

[ <a href="<?php echo $this->url(array('controller'=>'shortcuts','action'=>'delete','id'=>$this->shortcut->getId(),'delete'=>'true'),'default',true)?>">Yes</a> ] [ <a href="<?php echo $this->url(array('controller'=>'shortcuts','action'=>'index'),'default',true)?>">No</a> ]