<h1>Export Shortcuts</h1>
<h2>How to Download</h2>
<p>Please <a href="<?php echo $this->csv_file_path;?>">click here</a> to save your exported CSV file.</p>

<h2>How to Use</h2>
<p>The first line contains the headings for each column, and so should not be processed as data.</p>
<p>Following the first line, each line within the file represents a shortcut and contains the following fields:</p>

<dl>
   <dt>Section</dt>
   <dd>The section in which the shortcut is listed (eg. for Firefox: "Windows and Tabs").</dd>

   <dt>Shortcut</dt>
   <dd>The keyboard shortcut combination itself.</dd>

   <dt>Windows Override</dt>
   <dd>States a shortcut combination that may be specific to the Windows version of the appplication.</dd>

   <dt>Mac Override</dt>
   <dd>States a shortcut combination that may be specific to the Mac OS version of the appplication.</dd>

   <dt>Linux Override</dt>
   <dd>States a shortcut combination that may be specific to the Linux version of the appplication.</dd>

   <dt>Action</dt>
   <dd>The action that takes place as a result of the user pressing the keyboard shortcut.</dd>

   <dt>Notes</dt>
   <dd>Additional notes relevant to the shortcut.</dd>
</dl>

<h2>So what do you expect me to do with the data now?</h2>

<p>To be honest, we have no idea!</p>
<p>However, it's quite a simple feature for us to code and offer you, so we felt we could at least give you the ability and see if you have any ideas.</p>
<p>If you do, we'd love to hear how you've used it.</p>